<a href="https://colab.research.google.com/github/Shivavaraprasad6/TNS-Practice--session/blob/main/TASK_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [ ]:
data = {
    'Book_ID':[101,102,103,104,105],
    'Book_Name':['Python','DS','AI','Machine Learning', 'Database Systems'],
    'Category':['Programming','Programming','AI','AI','DBMS'],
    'Borrow_Count':[150,200,180,220,120],
    'Rating':[4.5,4.8,4.7,4.9,4.3]
}

df = pd.DataFrame(data)

df

   Book_ID         Book_Name     Category  Borrow_Count  Rating
0      101            Python  Programming           150     4.5
1      102                DS  Programming           200     4.8
2      103                AI           AI           180     4.7
3      104  Machine Learning           AI           220     4.9
4      105  Database Systems         DBMS           120     4.3

In [ ]:

df.describe()

          Book_ID  Borrow_Count    Rating
count    5.000000      5.000000  5.000000
mean   103.000000    174.000000  4.640000
std      1.581139     39.749214  0.240832
min    101.000000    120.000000  4.300000
25%    102.000000    150.000000  4.500000
50%    103.000000    180.000000  4.700000
75%    104.000000    200.000000  4.800000
max    105.000000    220.000000  4.900000

In [ ]:
#Handle Missing Values
df.isnull().sum()

Book_ID         0
Book_Name       0
Category        0
Borrow_Count    0
Rating          0
dtype: int64

In [ ]:
df['Borrow_Count'] = df['Borrow_Count'].fillna(df['Borrow_Count'].mean())
df['Rating'] = df['Rating'].fillna(df['Rating'].mean())

In [ ]:
#Remove Duplicates
df.drop_duplicates(inplace=True)
df

   Book_ID         Book_Name     Category  Borrow_Count  Rating
0      101            Python  Programming           150     4.5
1      102                DS  Programming           200     4.8
2      103                AI           AI           180     4.7
3      104  Machine Learning           AI           220     4.9
4      105  Database Systems         DBMS           120     4.3

In [ ]:
avg_borrow = df['Borrow_Count'].mean()

print(avg_borrow)

174.0

In [ ]:
#Find Books Borrowed More Than Average
avg_borrow = df['Borrow_Count'].mean()
df[df['Borrow_Count'] > avg_borrow]

,Book_ID,Book_Name,Category,Borrow_Count,Rating,Popularity_Index
1,102,DS,Programming,200,4.8,9.60
2,103,AI,AI,180,4.7,8.46
3,104,Machine Learning,AI,220,4.9,10.78

In [ ]:
#Sort by Borrow Count
df.sort_values(by='Borrow_Count', ascending=False)

   Book_ID         Book_Name     Category  Borrow_Count  Rating
3      104  Machine Learning           AI           220     4.9
1      102                DS  Programming           200     4.8
2      103                AI           AI           180     4.7
0      101            Python  Programming           150     4.5
4      105  Database Systems         DBMS           120     4.3

In [ ]:
#Find Category-wise Average Ratings
df.groupby('Category')['Rating'].mean()

Category
AI             4.80
DBMS           4.30
Programming    4.65
Name: Rating, dtype: float64

In [ ]:
#Create Popularity Index
df['Popularity_Index'] = (df['Borrow_Count'] * df['Rating']) / 100

df

,Book_ID,Book_Name,Category,Borrow_Count,Rating,Popularity_Index
0,101,Python,Programming,150,4.5,6.75
1,102,DS,Programming,200,4.8,9.60
2,103,AI,AI,180,4.7,8.46
3,104,Machine Learning,AI,220,4.9,10.78
4,105,Database Systems,DBMS,120,4.3,5.16

In [ ]:
#numpy functions
np.max(df['Borrow_Count'])

220

In [ ]:
np.min(df['Borrow_Count'])

120

In [ ]:
np.mean(df['Rating'])

np.float64(4.64)

In [ ]:
np.std(df['Rating'])

0.21540659228538028

In [ ]:
#Identify the Most Borrowed Book
df.loc[df['Borrow_Count'].idxmax()]

Book_ID                          104
Book_Name           Machine Learning
Category                          AI
Borrow_Count                     220
Rating                           4.9
Popularity_Index               10.78
Name: 3, dtype: object

In [ ]:
#Generate Report
print("===== LIBRARY REPORT =====")

print("Total Books:", len(df))

print("Average Borrow Count:",
      df['Borrow_Count'].mean())

print("Most Borrowed Book:",
      df.loc[df['Borrow_Count'].idxmax(),'Book_Name'])

print("Highest Borrow Count:",
      df['Borrow_Count'].max())

print("\nCategory-wise Average Ratings")
print(df.groupby('Category')['Rating'].mean())

===== LIBRARY REPORT =====
Total Books: 5
Average Borrow Count: 174.0
Most Borrowed Book: Machine Learning
Highest Borrow Count: 220

Category-wise Average Ratings
Category
AI             4.80
DBMS           4.30
Programming    4.65
Name: Rating, dtype: float64